### ISSUE TITLE
AcpiBacklight Panel not found.....aborting

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-ACPI-Backlight#17]
Hi, in 10.10 i get this error, so i don't have brightness control. Latest AcpiBacklight.kext and Fix to DSDT are on. Bye :>

**Comment by RehabMan** [comment]
You will get ""ACPIBacklightPanel not found... aborting" in system.log from the BacklightHandler object if you have an intel graphics device, but no PNLF in ACPI.  It happens because the ""ACPIBacklightPanel" object is not loading.  ACPIBacklightPanel matches on PNLF.

You have something wrong with your patched ACPI set, or forgot to Drop OEM SSDTs.
